services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jobs_app
    container_name: jobs_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:stable-alpine
    container_name: jobs_nginx
    ports:
        - "80:80"
        - '${SSL_PORT:-443}:443'
    environment:
        - SSL_PORT=${SSL_PORT:-443}
        - APP_SERVICE=${APP_SERVICE:-jobs.dev}
        - SERVER_NAME=${SERVER_NAME:-localhost}
        - SSL_DOMAIN=${SSL_DOMAIN:-localhost}
        - SSL_ALT_NAME=${SSL_ALT_NAME:-DNS:localhost}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: jobs_mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_DATABASE:     'jobs'
        MYSQL_ROOT_HOST:    '%'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
